### ISSUE TITLE
how ?

### ISSUE THREAD

**Issue by icepy** [kzaher/RegX#5]
command + F1 F2 F3 ti's not  work  , please give me  some help or tips. tkx

**Comment by kzaher** [comment]
Hm, do you see any it in edit menu? If not, then plugin isn't loaded.

**Comment by kzaher** [comment]
There is usually a problem with xcode DVTPlugInCompatibilityUUID.  If alcatraz doesn't work, just please clone the repository and hit run, and restart xcode, and it should work.

Xcode has a really stupid thing with those IDs, but I've set it up so that when you build the project, it will immediately update the plist with DVTPlugInCompatibilityUUID of the xcode that is used to build it. 

Hope this helps.

**Comment by icepy** [comment]
ye, thx for help.
